window.DEADPUNK_PROJECTS = [
  {
    id: "adam",
    module: "ADAM.depth",
    title: "A.D.A.M.",
    subtitle: "Adaptive Depth and Mode",
    type: "AI control protocol",
    job: "Keeps AI chats at the right depth.",
    problem: "Simple questions stay simple. Complex work does not become unclear or overloaded.",
    output: "LOW / MID / DEEP response control.",
    repo: "https://github.com/XxYouDeaDPunKxX/A.D.A.M.-Adaptive-Depth-and-Mode",
    note: "overthinking containment unit",
    icon: "dial"
  },
  {
    id: "memory-assisted-shaping",
    module: "MEMORY_SHAPER.session",
    title: "Memory-Assisted Shaping",
    subtitle: "Long-session shaping protocol",
    type: "AI continuity protocol",
    job: "Keeps long idea-shaping sessions coherent.",
    problem: "Decisions, gates, discarded paths, and source boundaries get lost before the final artifact is ready.",
    output: "Cleaner final artifacts after controlled shaping.",
    repo: "https://github.com/XxYouDeaDPunKxX/Memory-Assisted-Shaping",
    note: "drift repellent, probably flammable",
    icon: "tape"
  },
  {
    id: "pa-pvp",
    module: "PA_PVP.decision",
    title: "PA-PVP",
    subtitle: "Adversarial Peer Validation Protocol",
    type: "Decision loop",
    job: "Turns vague plans, artifacts, or stuck decisions into an operational next move.",
    problem: "Open-ended discussion keeps replacing closure.",
    output: "Verdict, one next action, and a continuation point.",
    repo: "https://github.com/XxYouDeaDPunKxX/PA_PVP-a-PLUTONIUM-like-Adversarial-Peer-Validation-Protocol",
    note: "argues so you do not have to",
    icon: "scale"
  },
  {
    id: "pa-pvp-mini",
    module: "PA_PVP_MINI.review",
    title: "PA-PVP mini",
    subtitle: "Lightweight adversarial review",
    type: "Review protocol",
    job: "Stress-tests ideas, plans, prompts, procedures, code, and AI outputs.",
    problem: "Plausible material can hide gaps, weak logic, missing constraints, and shaky fixes.",
    output: "Concrete findings and structural fixes.",
    repo: "https://github.com/XxYouDeaDPunKxX/PA-PVP-mini",
    note: "small, sharp, mildly annoying",
    icon: "lens"
  },
  {
    id: "signal-rail",
    module: "SIGNAL_RAIL.routing",
    title: "Signal Rail",
    subtitle: "Plain-text document governance",
    type: "Document routing system",
    job: "Keeps live project material in the right place.",
    problem: "Decisions, open work, ideas, constraints, and handoff notes collapse into one messy document.",
    output: "Separated rails for state, decisions, ideas, constraints, handoff, parking, and archive.",
    repo: "https://github.com/XxYouDeaDPunKxX/Signal-Rail",
    note: "keeps mess on tracks",
    icon: "rail"
  },
  {
    id: "csbp",
    module: "CSBP.practice_filter",
    title: "CSBP",
    subtitle: "Codex Shared Best Practice",
    type: "Practice filter",
    job: "Keeps reusable Codex practices explicit, reviewed, and controlled.",
    problem: "Useful guidance either stays buried in chat history or gets promoted too quickly into project rules.",
    output: "A small companion layer for practices worth reusing, but not strong enough to become project rules.",
    repo: "https://github.com/XxYouDeaDPunKxX/CSBP-Codex-Shared-Best-Practice",
    note: "not a rule, not a vibe",
    icon: "filter"
  },
  {
    id: "sensecraftxstudio",
    module: "SENSECRAFT.frame",
    title: "SensecraftXStudio",
    subtitle: "AI-assisted technical work frame",
    type: "Grounding frame",
    job: "Keeps AI-assisted technical work grounded before the assistant acts.",
    problem: "The assistant can stay plausible after the frame has drifted.",
    output: "Visible target, context, assumptions, action boundary, and final state.",
    repo: "https://github.com/XxYouDeaDPunKxX/SensecraftXStudio",
    note: "confidence not trusted here",
    icon: "frame"
  },
  {
    id: "project-forge",
    module: "PROJECT_FORGE.bootloader",
    title: "GPT-PF / ChatGPT Project Forge",
    subtitle: "Project opening package builder",
    type: "Project bootloader",
    job: "Prepares starting files for a ChatGPT Project.",
    problem: "Projects start from memory, chat momentum, or informal notes instead of explicit files.",
    output: "Scope, sources, constraints, and starting basis before the real work begins.",
    repo: "https://github.com/XxYouDeaDPunKxX/GPT-PF-Chat-GPT-Project-Forge",
    note: "boots before it pretends",
    icon: "boot"
  }
];
