window.DEADPUNK_PROJECTS = [
  {
    id: "adam",
    module: "ADAM.depth",
    title: "A.D.A.M.",
    subtitle: "Adaptive Depth and Mode",
    type: "AI control protocol",
    category: "AI protocols",
    route: "AI response misses depth or starts hallucinating",
    job: "Keeps AI chats at the right depth.",
    problem: "Simple questions stay simple. Complex work does not become unclear or overloaded.",
    output: "LOW / MID / DEEP response control.",
    repo: "https://github.com/XxYouDeaDPunKxX/A.D.A.M.-Adaptive-Depth-and-Mode",
    note: "overthinking containment unit",
    icon: "dial"
  },
  {
    id: "ai-protocol-kit",
    module: "AI_PROTOCOL_KIT.contracts",
    title: "ai-protocol-kit",
    subtitle: "AI behavior contracts and operational protocols",
    type: "AI protocol kit",
    category: "AI protocols",
    route: "AI-assisted work keeps breaking from vague prompts or hidden assumptions",
    job: "Gives AI sessions task-specific operating contracts.",
    problem: "Normal prompts can let AI rush, assume, lose context, write for the wrong reader, or publish before review.",
    output: "Reusable protocols for shaping, reviewing, publishing, and reader-facing output.",
    repo: "https://github.com/XxYouDeaDPunKxX/ai-protocol-kit",
    note: "not magic prompts, working contracts",
    icon: "filter"
  },
  {
    id: "memory-assisted-shaping",
    module: "MEMORY_SHAPER.session",
    title: "Memory-Assisted Shaping",
    subtitle: "Long-session shaping protocol",
    type: "AI continuity protocol",
    category: "AI protocols",
    route: "long idea-shaping session starts drifting",
    job: "Keeps long idea-shaping sessions coherent.",
    problem: "Decisions, gates, discarded paths, and source boundaries get lost before the final artifact is ready.",
    output: "Cleaner final artifacts after controlled shaping.",
    repo: "https://github.com/XxYouDeaDPunKxX/Memory-Assisted-Shaping",
    note: "drift repellent, probably flammable",
    icon: "tape"
  },
  {
    id: "pa-pvp",
    module: "PA_PVP.decision",
    title: "PA-PVP",
    subtitle: "Adversarial Peer Validation Protocol",
    type: "Decision protocol",
    category: "decision systems",
    route: "indecision keeps the work moving without deciding",
    job: "Turns vague plans, artifacts, or stuck decisions into an operational next move.",
    problem: "Open-ended discussion keeps replacing closure.",
    output: "Verdict, one next action, and a continuation point.",
    repo: "https://github.com/XxYouDeaDPunKxX/PA_PVP-a-PLUTONIUM-like-Adversarial-Peer-Validation-Protocol",
    note: "argues so you do not have to",
    icon: "scale"
  },
  {
    id: "pa-pvp-mini",
    module: "PA_PVP_MINI.review",
    title: "PA-PVP mini",
    subtitle: "Lightweight adversarial review",
    type: "Adversarial review protocol",
    category: "review systems",
    route: "idea or output looks plausible but structurally weak",
    job: "Stress-tests ideas, plans, prompts, procedures, code, and AI outputs.",
    problem: "Plausible material can hide gaps, weak logic, missing constraints, and shaky fixes.",
    output: "Concrete findings and structural fixes.",
    repo: "https://github.com/XxYouDeaDPunKxX/PA-PVP-mini",
    note: "small, sharp, mildly annoying",
    icon: "lens"
  },
  {
    id: "signal-rail",
    module: "SIGNAL_RAIL.routing",
    title: "Signal Rail",
    subtitle: "Plain-text document governance",
    type: "Document routing system",
    category: "document governance",
    route: "project documents become a pile",
    job: "Keeps live project material in the right place.",
    problem: "Decisions, open work, ideas, constraints, and handoff notes collapse into one messy document.",
    output: "Separated rails for state, decisions, ideas, constraints, handoff, parking, and archive.",
    repo: "https://github.com/XxYouDeaDPunKxX/Signal-Rail",
    note: "keeps mess on tracks",
    icon: "rail"
  },
  {
    id: "csbp",
    module: "CSBP.practice_filter",
    title: "CSBP",
    subtitle: "Codex Shared Best Practice",
    type: "Practice governance",
    category: "Codex environment discipline",
    route: "Codex keeps making the same mistakes; discipline the work environment",
    job: "Keeps reusable Codex practices explicit, reviewed, and controlled.",
    problem: "Useful guidance either stays buried in chat history or gets promoted too quickly into project rules.",
    output: "A small companion layer for practices worth reusing, but not strong enough to become project rules.",
    repo: "https://github.com/XxYouDeaDPunKxX/CSBP-Codex-Shared-Best-Practice",
    note: "not a rule, not a vibe",
    icon: "filter"
  },
  {
    id: "sensecraftxstudio",
    module: "SENSECRAFT.frame",
    title: "SensecraftXStudio",
    subtitle: "AI-assisted technical work frame",
    type: "Agent behavior contract",
    category: "agent contracts",
    route: "Codex needs to slow down and clear the frame before touching the work",
    job: "Keeps AI-assisted technical work grounded before the assistant acts.",
    problem: "The assistant can stay plausible after the frame has drifted.",
    output: "Visible target, context, assumptions, action boundary, and final state.",
    repo: "https://github.com/XxYouDeaDPunKxX/SensecraftXStudio",
    note: "confidence not trusted here",
    icon: "frame"
  },
  {
    id: "project-forge",
    module: "PROJECT_FORGE.bootloader",
    title: "GPT-PF / ChatGPT Project Forge",
    subtitle: "Project opening package builder",
    type: "ChatGPT project bootloader",
    category: "ChatGPT project setup hygiene",
    route: "new ChatGPT project starts from fog",
    job: "Prepares starting files for a ChatGPT Project.",
    problem: "Projects start from memory, chat momentum, or informal notes instead of explicit files.",
    output: "Scope, sources, constraints, and starting basis before the real work begins.",
    repo: "https://github.com/XxYouDeaDPunKxX/GPT-PF-Chat-GPT-Project-Forge",
    note: "boots before it pretends",
    icon: "boot"
  },
  {
    id: "cloudflare-r2-remote-mcp-worker",
    module: "R2_MCP.bucket",
    title: "Cloudflare R2 Remote MCP Worker",
    subtitle: "Let ChatGPT fetch files, upload stuff, and then ask: wait, where did that come from?",
    type: "Cloud file storage bridge + authenticated remote MCP",
    category: "AI storage tools",
    route: "ChatGPT needs files, but your local disk is not invited",
    job: "Gives ChatGPT-style MCP clients a controlled remote place to read and write files.",
    problem: "ChatGPT does not work like a local desktop app with direct disk access. If it needs files through MCP, the endpoint has to be reachable remotely.",
    output: "A Cloudflare Worker that connects ChatGPT to Cloudflare R2 storage through remote MCP tools, protected by GitHub OAuth.",
    repo: "https://github.com/XxYouDeaDPunKxX/cloudflare-r2-remote-mcp-worker",
    note: "tiny cloud closet, because local disk access was not invited",
    icon: "r2"
  },
  {
    id: "canon-boundary-guard",
    module: "CANON_BOUNDARY.guard",
    title: "Canon Boundary Guard",
    subtitle: "Codex provenance boundary skill",
    type: "Codex skill",
    category: "Codex environment discipline",
    route: "Codex must keep project evidence, chat context, instructions, hypotheses, and model assumptions separate",
    job: "Keeps Codex source layers separated during long or consequential sessions.",
    problem: "Project evidence, temporary chat, agent-control instructions, working hypotheses, and model priors can collapse into one authority layer.",
    output: "A Codex skill folder with a classification frame, compact injected frame, and highly recommended PreToolUse hook.",
    repo: "https://github.com/XxYouDeaDPunKxX/canon-boundary-guard-codex",
    note: "keeps the voices in their lanes",
    icon: "canon"
  }
];
