window.DEADPUNK_PROJECTS = [
  {
    id: "adam",
    module: "ADAM.depth",
    title: "A.D.A.M.",
    subtitle: "Adaptive Depth and Mode",
    type: "Plain-text AI protocol",
    category: "response depth control",
    route: "AI response either hallucinates or brings a forklift to a teaspoon job",
    job: "Sets the answer depth before the chat starts digging its own grave.",
    problem: "Tiny questions get autopsied. Hard ones get waved through with a smile and a missing organ.",
    output: "LOW / MID / DEEP response control, with fewer theatrical collapses.",
    repo: "https://github.com/XxYouDeaDPunKxX/A.D.A.M.-Adaptive-Depth-and-Mode",
    note: "overthinking containment unit, lid not included",
    icon: "dial"
  },
  {
    id: "ai-protocol-kit",
    module: "AI_PROTOCOL_KIT.contracts",
    title: "ai-protocol-kit",
    subtitle: "AI behavior contracts and operational protocols",
    type: "Protocol collection",
    category: "AI work governance",
    route: "AI-assisted work keeps dying from vague prompts, hidden assumptions, and optimism",
    job: "Hands the session a contract before it starts renovating the crime scene.",
    problem: "Without rails, AI rushes, assumes, publishes, and calls the debris a workflow.",
    output: "Reusable protocols for shaping, reviewing, publishing, and reader-facing output.",
    repo: "https://github.com/XxYouDeaDPunKxX/ai-protocol-kit",
    note: "not magic prompts; paperwork with teeth",
    icon: "filter"
  },
  {
    id: "memory-assisted-shaping",
    module: "MEMORY_SHAPER.gpt_project",
    title: "Memory-Assisted Shaping for GPT Project",
    subtitle: "Long-session shaping protocol for GPT Projects",
    type: "ChatGPT Project protocol",
    category: "long-session continuity",
    route: "long GPT Project session starts forgetting which corpse was the original idea",
    job: "Keeps long shaping sessions from wandering off with the wrong decision.",
    problem: "Gates, discarded paths, and source boundaries vanish; the final artifact inherits the whole crime scene.",
    output: "Cleaner final artifacts after controlled shaping, with fewer ghosts in the walls.",
    repo: "https://github.com/XxYouDeaDPunKxX/Memory-Assisted-Shaping",
    note: "drift repellent, probably flammable",
    icon: "tape"
  },
  {
    id: "pa-pvp",
    module: "PA_PVP.decision",
    title: "PA-PVP",
    subtitle: "Adversarial Peer Validation Protocol",
    type: "Adversarial decision protocol",
    category: "decision closure",
    route: "indecision keeps the work moving without deciding, like a meeting with a pulse",
    job: "Turns vague plans, artifacts, and stuck decisions into one executable next move.",
    problem: "Open-ended discussion keeps wearing different hats and pretending one of them is closure.",
    output: "Verdict, next action, probes, debt, and a continuation point.",
    repo: "https://github.com/XxYouDeaDPunKxX/PA_PVP-a-PLUTONIUM-like-Adversarial-Peer-Validation-Protocol",
    note: "argues so you do not have to, then invoices your certainty",
    icon: "scale"
  },
  {
    id: "pa-pvp-mini",
    module: "PA_PVP_MINI.review",
    title: "PA-PVP mini",
    subtitle: "Lightweight adversarial review",
    type: "Lightweight review protocol",
    category: "adversarial review",
    route: "idea looks plausible, which is how most bad ideas enter the building",
    job: "Stress-tests ideas, plans, prompts, procedures, code, and AI outputs.",
    problem: "Plausible material hides weak logic, missing constraints, and dead batteries under a clean shirt.",
    output: "Concrete findings and structural fixes before the corpse reaches production.",
    repo: "https://github.com/XxYouDeaDPunKxX/PA-PVP-mini",
    note: "small, sharp, mildly annoying",
    icon: "lens"
  },
  {
    id: "signal-rail",
    module: "SIGNAL_RAIL.routing",
    title: "Signal Rail",
    subtitle: "Plain-text document governance",
    type: "Plain-text routing system",
    category: "document state control",
    route: "project documents become a pile and start breeding in the corner",
    job: "Keeps live project material in the right place before the notes turn into landfill.",
    problem: "Decisions, open work, ideas, constraints, handoff notes, and archive dust collapse into one document-shaped swamp.",
    output: "Separated rails for state, decisions, ideas, constraints, handoff, parking, and archive.",
    repo: "https://github.com/XxYouDeaDPunKxX/Signal-Rail",
    note: "keeps mess on tracks; still smells like work",
    icon: "rail"
  },
  {
    id: "csbp",
    module: "CSBP.practice_filter",
    title: "CSBP",
    subtitle: "Codex Shared Best Practice",
    type: "Three-file governance layer",
    category: "Codex practice memory",
    route: "Codex keeps making the same mistake until it becomes office furniture",
    job: "Keeps reusable Codex practices explicit, reviewed, and controlled.",
    problem: "Useful guidance either rots in chat history or gets promoted too fast into project law.",
    output: "A companion layer for practices worth reusing, but not strong enough to become project rules.",
    repo: "https://github.com/XxYouDeaDPunKxX/CSBP-Codex-Shared-Best-Practice",
    note: "not a rule, not a vibe, not another sacred sticky note",
    icon: "filter"
  },
  {
    id: "sensecraftxstudio",
    module: "SENSECRAFT.frame",
    title: "SensecraftXStudio",
    subtitle: "AI-assisted technical work frame",
    type: "Agent behavior contract",
    category: "technical work framing",
    route: "Codex is about to touch the work while the frame is already smoking",
    job: "Forces AI-assisted technical work to clear target, context, assumptions, and action boundary before touching files.",
    problem: "The assistant can stay confident long after the frame has quietly died under the desk.",
    output: "Visible target, context, assumptions, action boundary, and final state.",
    repo: "https://github.com/XxYouDeaDPunKxX/SensecraftXStudio",
    note: "confidence not trusted here; bring evidence or a shovel",
    icon: "frame"
  },
  {
    id: "project-forge",
    module: "PROJECT_FORGE.bootloader",
    title: "GPT-PF / ChatGPT Project Forge",
    subtitle: "Project opening package builder",
    type: "Project starter package",
    category: "ChatGPT Project bootstrap",
    route: "new ChatGPT Project starts from fog, vibes, and a folder named final_final",
    job: "Prepares explicit starting files before the Project pretends memory is a plan.",
    problem: "Projects start from chat momentum, loose notes, or mystical continuity and then act surprised when the walls move.",
    output: "Scope, sources, constraints, and starting basis before the real work begins.",
    repo: "https://github.com/XxYouDeaDPunKxX/GPT-PF-Chat-GPT-Project-Forge",
    note: "boots before it pretends",
    icon: "boot"
  },
  {
    id: "chatgpt-skill-system",
    module: "GPT_SKILLS.session_loader",
    title: "GPT Project Skill System",
    subtitle: "Skill-style capability loading for ChatGPT Projects",
    type: "Session skill loader",
    category: "ChatGPT capability extension",
    route: "ChatGPT wants skills, but the native slot is missing and everyone keeps taping instructions to the wall",
    job: "Gives a ChatGPT Project a controlled way to unpack, validate, and load only the skill needed for the current session.",
    problem: "ChatGPT Projects can hold files, but not native skills. This adds a controlled session workflow for loading skill-like packages without dumping everything into context.",
    output: "A Project-ready skill workflow: core boot, explicit skill loading, and adapter reports for checking whether external skills can run inside ChatGPT.",
    repo: "https://github.com/XxYouDeaDPunKxX/ChatGPT-SKILL-SYSTEM",
    note: "skill slot sold separately; this bolts one on without pretending it is magic",
    icon: "gpt"
  },
  {
    id: "cloudflare-r2-remote-mcp-worker",
    module: "R2_MCP.bucket",
    title: "Cloudflare R2 Remote MCP Worker",
    subtitle: "Let ChatGPT fetch files, upload stuff, and then ask: wait, where did that come from?",
    type: "Cloudflare Worker MCP server",
    category: "remote file access",
    route: "ChatGPT needs files, but your local disk is not invited",
    job: "Gives ChatGPT-style MCP clients a controlled remote place to read and write files.",
    problem: "ChatGPT does not work like a local desktop app with direct disk access. If it needs files through MCP, the endpoint has to be reachable remotely.",
    output: "A Cloudflare Worker that connects ChatGPT to Cloudflare R2 storage through remote MCP tools, protected by GitHub OAuth.",
    repo: "https://github.com/XxYouDeaDPunKxX/cloudflare-r2-remote-mcp-worker",
    note: "tiny cloud closet, because local disk access was not invited",
    icon: "r2"
  },
  {
    id: "canon-boundary-guard-codex",
    module: "CANON_BOUNDARY.codex",
    title: "Canon Boundary Guard for Codex",
    subtitle: "Codex provenance boundary plugin and skill",
    type: "Codex plugin and skill",
    category: "Codex provenance control",
    route: "Codex starts mixing repo evidence, chat residue, AGENTS instructions, and vibes",
    job: "Keeps Codex source layers separated before it edits the repo like a haunted intern.",
    problem: "Project evidence, chat context, agent-control instructions, working hypotheses, and model priors collapse into one authority soup.",
    output: "A Codex plugin/skill with a compact frame and highly recommended PreToolUse hook.",
    repo: "https://github.com/XxYouDeaDPunKxX/canon-boundary-guard-codex",
    note: "keeps the voices in their lanes, with a clipboard and a warning label",
    icon: "canon"
  },
  {
    id: "canon-boundary-guard-gpt-project",
    module: "CANON_BOUNDARY.gpt_project",
    title: "Canon Boundary Guard for GPT Projects",
    subtitle: "ChatGPT Project provenance boundary frame",
    type: "Project source bundle",
    category: "ChatGPT provenance control",
    route: "ChatGPT Project turns uploads, chat, and assumptions into one cursed soup",
    job: "Keeps files, chat, instructions, drafts, and assumptions in separate lanes.",
    problem: "A Project can start treating files, old chat, fresh drafts, and model guesses as the same authority wearing different shoes.",
    output: "A zipped source bundle and Project Instructions for long ChatGPT sessions.",
    repo: "https://github.com/XxYouDeaDPunKxX/canon-boundary-guard-for-gpt-project",
    note: "source separation for chats that keep adopting every stray thought",
    icon: "gpt"
  },
  {
    id: "shaping-frame-for-claude",
    module: "SHAPING_FRAME.claude",
    title: "Shaping Frame for Claude",
    subtitle: "Cognitive layer for Claude chats",
    type: "Claude skill package",
    category: "Claude epistemic framing",
    route: "Claude chat starts treating a fresh guess like a signed death certificate",
    job: "Keeps Claude aware of what is hypothesis, decision, or unvalidated generated material.",
    problem: "Normal Claude chats can smooth over uncertainty until everything sounds already settled and ready for burial.",
    output: "A Claude skill plus custom instructions for epistemic weight in long sessions.",
    repo: "https://github.com/XxYouDeaDPunKxX/shaping-frame-for-claude",
    note: "polite uncertainty cage for a model with good manners",
    icon: "claude"
  }
];
